const QUESTIONS_REQUEST = `QUESTIONS_REQUEST`;
const ERROR_SET = `ERROR_SET`;
const ERROR_RESET = `ERROR_RESET`;
const NAME_SET = `NAME_SET`;
const ANSWER_ADD = `ANSWER_ADD`;

export default {
  QUESTIONS_REQUEST,
  ERROR_SET,
  ERROR_RESET,
  NAME_SET,
  ANSWER_ADD
};
