const REQUEST_QUESTIONS = `REQUEST_QUESTIONS`;
const ERROR_SET = `ERROR_SET`;
const ERROR_RESET = `ERROR_RESET`;
const NAME_SET = `NAME_SET`;

export default {
  REQUEST_QUESTIONS,
  ERROR_SET,
  ERROR_RESET,
  NAME_SET,
};
